### ISSUE TITLE
ScrollText not displaying in Adobe AIR 18 beta

### ISSUE THREAD

**Issue by grosssmutttr** [joshtynjala/feathers#1125] opened 2015-04-29 14:04 UTC
Hi there,

I haven't been able to update my app since AIR 16 because of the Texture mismatch bug.
Now the new AIR 18 beta managed to solve the problem but unfortunately the ScrollText isn't visible anymore.

Tested this with a Nexus 4 with Android 5.1.

When I minimize and maximize the app the text appears...

Any ideas?

**Comment by joshtynjala** [comment] 2015-05-05 18:30
I've seen other reports of text failing to display in AIR 18. I seems to be a bug on Adobe's side.

**Comment by joshtynjala** [comment] 2015-05-05 19:49
Strangely, though, I cannot reproduce this issue on my Nexus 5 with Android 5.1. I wonder what is different about my environment.

**Comment by grosssmutttr** [comment] 2015-05-07 08:26
On a Samsung Galaxy S2 running Android 4.1.2 I'm getting:

ArgumentError: Error #3672: Buffer creation failed. Internal error.
at flash.display3D::Context3D/createVertexBuffer()
at starling.display::QuadBatch/createBuffers()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/QuadBatch.as:174]
at starling.display::QuadBatch/syncBuffers()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/QuadBatch.as:203]
at starling.display::QuadBatch/renderCustom()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/QuadBatch.as:221]
at starling.core::RenderSupport/finishQuadBatch()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/RenderSupport.as:501]
at starling.display::QuadBatch/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/QuadBatch.as:474]
at starling.display::DisplayObjectContainer/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/DisplayObjectContainer.as:360]
at starling.display::Sprite/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/Sprite.as:238]
at feathers.display::Scale9Image/render()[/Users/joshtynjala/Development/Flash/feathers/source/feathers/display/Scale9Image.as:462]
at starling.display::DisplayObjectContainer/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/DisplayObjectContainer.as:360]
at starling.display::Sprite/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/Sprite.as:238]
at feathers.controls::Button/render()[/Users/joshtynjala/Development/Flash/feathers/source/feathers/controls/Button.as:2208]
at starling.display::DisplayObjectContainer/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/DisplayObjectContainer.as:360]
at starling.display::Sprite/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/Sprite.as:238]
at starling.display::DisplayObjectContainer/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/DisplayObjectContainer.as:360]
at starling.display::Sprite/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/Sprite.as:238]
at feathers.controls::LayoutGroup/render()[/Users/joshtynjala/Development/Flash/feathers/source/feathers/controls/LayoutGroup.as:564]
at starling.display::DisplayObjectContainer/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/DisplayObjectContainer.as:360]
at starling.display::Sprite/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/Sprite.as:238]
at starling.display::DisplayObjectContainer/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/display/DisplayObjectContainer.as:360]
at starling.core::Starling/render()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:514]
at starling.core::Starling/nextFrame()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:469]
at starling.core::Starling/onEnterFrame()[/Users/redge/Dropbox/Development/starling/starling/src/starling/core/Starling.as:682]

**Comment by joshtynjala** [comment] 2015-05-07 16:45
The buffer creation failed error sounds like the issues described here: http://forum.starling-framework.org/topic/heads-up-air-17-causes-problems-on-android

**Comment by joshtynjala** [comment] 2015-06-15 19:48
Everything seems to be working correctly with ScrollText using the stable AIR 18.0.0.143 release on my Nexus 5, so I'm closing.

**Closed by joshtynjala** 2015-06-15 19:48 UTC

**Comment by grosssmutttr** [comment] 2015-06-16 06:24
You're right that the ScrollText is working now but unfortunately the UI Buttons now become black squares if you close an interstitial ad. UI Text is still visible.
This doesn't occur on the Nexus 4 but sometimes (often) happens on a Samsung Galaxy S2 and S3.

I'm using the milkmangames AdMob extension.
